//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterExcelDirPath {
            get {
                return ((string)(this["FuncCSVConverterExcelDirPath"]));
            }
            set {
                this["FuncCSVConverterExcelDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathServer {
            get {
                return ((string)(this["FuncCSVConverterDirPathServer"]));
            }
            set {
                this["FuncCSVConverterDirPathServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathClient {
            get {
                return ((string)(this["FuncCSVConverterDirPathClient"]));
            }
            set {
                this["FuncCSVConverterDirPathClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text.xlsx")]
        public string FuncCSVConverterTextName {
            get {
                return ((string)(this["FuncCSVConverterTextName"]));
            }
            set {
                this["FuncCSVConverterTextName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main")]
        public string FuncCSVConverterSheetName {
            get {
                return ((string)(this["FuncCSVConverterSheetName"]));
            }
            set {
                this["FuncCSVConverterSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterExistLineFour {
            get {
                return ((bool)(this["FuncCSVConverterExistLineFour"]));
            }
            set {
                this["FuncCSVConverterExistLineFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncTextDiffOldTextPath {
            get {
                return ((string)(this["FuncTextDiffOldTextPath"]));
            }
            set {
                this["FuncTextDiffOldTextPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncTextDiffNewTextPath {
            get {
                return ((string)(this["FuncTextDiffNewTextPath"]));
            }
            set {
                this["FuncTextDiffNewTextPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncTextDiffTextDifferencePath {
            get {
                return ((string)(this["FuncTextDiffTextDifferencePath"]));
            }
            set {
                this["FuncTextDiffTextDifferencePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main")]
        public string FuncTextDiffSheetName {
            get {
                return ((string)(this["FuncTextDiffSheetName"]));
            }
            set {
                this["FuncTextDiffSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal FuncTextDiffOldItemColor {
            get {
                return ((decimal)(this["FuncTextDiffOldItemColor"]));
            }
            set {
                this["FuncTextDiffOldItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal FuncTextDiffNewItemColor {
            get {
                return ((decimal)(this["FuncTextDiffNewItemColor"]));
            }
            set {
                this["FuncTextDiffNewItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncTextDiffExistLineFour {
            get {
                return ((bool)(this["FuncTextDiffExistLineFour"]));
            }
            set {
                this["FuncTextDiffExistLineFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerCustomPath {
            get {
                return ((string)(this["FuncCustomizerCustomPath"]));
            }
            set {
                this["FuncCustomizerCustomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerCustomSheetName {
            get {
                return ((string)(this["FuncCustomizerCustomSheetName"]));
            }
            set {
                this["FuncCustomizerCustomSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerInputFunctionDirPath {
            get {
                return ((string)(this["FuncCustomizerInputFunctionDirPath"]));
            }
            set {
                this["FuncCustomizerInputFunctionDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerOutputFunctionDirPath {
            get {
                return ((string)(this["FuncCustomizerOutputFunctionDirPath"]));
            }
            set {
                this["FuncCustomizerOutputFunctionDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerOldFunctionDirPath {
            get {
                return ((string)(this["FuncCustomizerOldFunctionDirPath"]));
            }
            set {
                this["FuncCustomizerOldFunctionDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCustomizerCustomClashPath {
            get {
                return ((string)(this["FuncCustomizerCustomClashPath"]));
            }
            set {
                this["FuncCustomizerCustomClashPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main")]
        public string FuncCustomizerFuncSheetName {
            get {
                return ((string)(this["FuncCustomizerFuncSheetName"]));
            }
            set {
                this["FuncCustomizerFuncSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal FuncCustomizerOldItemColor {
            get {
                return ((decimal)(this["FuncCustomizerOldItemColor"]));
            }
            set {
                this["FuncCustomizerOldItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal FuncCustomizerNewItemColor {
            get {
                return ((decimal)(this["FuncCustomizerNewItemColor"]));
            }
            set {
                this["FuncCustomizerNewItemColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCustomizerExistLineFour {
            get {
                return ((bool)(this["FuncCustomizerExistLineFour"]));
            }
            set {
                this["FuncCustomizerExistLineFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncVersionDiffOldExcelDirPath {
            get {
                return ((string)(this["FuncVersionDiffOldExcelDirPath"]));
            }
            set {
                this["FuncVersionDiffOldExcelDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncVersionDiffNewExcelDirPath {
            get {
                return ((string)(this["FuncVersionDiffNewExcelDirPath"]));
            }
            set {
                this["FuncVersionDiffNewExcelDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main")]
        public string FuncVersionDiffSheetName {
            get {
                return ((string)(this["FuncVersionDiffSheetName"]));
            }
            set {
                this["FuncVersionDiffSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncVersionDiffExistLineFour {
            get {
                return ((bool)(this["FuncVersionDiffExistLineFour"]));
            }
            set {
                this["FuncVersionDiffExistLineFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UISceneTextCsvPath {
            get {
                return ((string)(this["UISceneTextCsvPath"]));
            }
            set {
                this["UISceneTextCsvPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UISceneTextNewCsvPath {
            get {
                return ((string)(this["UISceneTextNewCsvPath"]));
            }
            set {
                this["UISceneTextNewCsvPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathCommonJS {
            get {
                return ((string)(this["FuncCSVConverterDirPathCommonJS"]));
            }
            set {
                this["FuncCSVConverterDirPathCommonJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseCSV {
            get {
                return ((bool)(this["FuncCSVConverterUseCSV"]));
            }
            set {
                this["FuncCSVConverterUseCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseJS {
            get {
                return ((bool)(this["FuncCSVConverterUseJS"]));
            }
            set {
                this["FuncCSVConverterUseJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseCommonJS {
            get {
                return ((bool)(this["FuncCSVConverterUseCommonJS"]));
            }
            set {
                this["FuncCSVConverterUseCommonJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FuncCSVConverterUseCSVString {
            get {
                return ((bool)(this["FuncCSVConverterUseCSVString"]));
            }
            set {
                this["FuncCSVConverterUseCSVString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseTypescript {
            get {
                return ((bool)(this["FuncCSVConverterUseTypescript"]));
            }
            set {
                this["FuncCSVConverterUseTypescript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathTypescript {
            get {
                return ((string)(this["FuncCSVConverterDirPathTypescript"]));
            }
            set {
                this["FuncCSVConverterDirPathTypescript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathProtobuffer {
            get {
                return ((string)(this["FuncCSVConverterDirPathProtobuffer"]));
            }
            set {
                this["FuncCSVConverterDirPathProtobuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseProtobuffer {
            get {
                return ((bool)(this["FuncCSVConverterUseProtobuffer"]));
            }
            set {
                this["FuncCSVConverterUseProtobuffer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FuncCSVConverterUseText {
            get {
                return ((bool)(this["FuncCSVConverterUseText"]));
            }
            set {
                this["FuncCSVConverterUseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathText {
            get {
                return ((string)(this["FuncCSVConverterDirPathText"]));
            }
            set {
                this["FuncCSVConverterDirPathText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FuncCSVConverterDirPathCSVString {
            get {
                return ((string)(this["FuncCSVConverterDirPathCSVString"]));
            }
            set {
                this["FuncCSVConverterDirPathCSVString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Id")]
        public string FuncCSVConverterTextColId {
            get {
                return ((string)(this["FuncCSVConverterTextColId"]));
            }
            set {
                this["FuncCSVConverterTextColId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string FuncCSVConverterTextColName {
            get {
                return ((string)(this["FuncCSVConverterTextColName"]));
            }
            set {
                this["FuncCSVConverterTextColName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SheetCopyOldExcelDirPath {
            get {
                return ((string)(this["SheetCopyOldExcelDirPath"]));
            }
            set {
                this["SheetCopyOldExcelDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SheetCopyNewExcelDirPath {
            get {
                return ((string)(this["SheetCopyNewExcelDirPath"]));
            }
            set {
                this["SheetCopyNewExcelDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SheetCopySheetName {
            get {
                return ((string)(this["SheetCopySheetName"]));
            }
            set {
                this["SheetCopySheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SheetCopyExistLineFour {
            get {
                return ((bool)(this["SheetCopyExistLineFour"]));
            }
            set {
                this["SheetCopyExistLineFour"] = value;
            }
        }
    }
}
